### ISSUE TITLE
add purs-tidy-module-name

### ISSUE THREAD

**Issue by srghma** [thomashoneyman/purescript-overlay#98]
I have a tool, I would like to add it to repo, I would like to add it

https://github.com/srghma/purs-utils

(but I'm still thinking about api)

**Comment by thomashoneyman** [comment]
Hi @srghma! I'm intentionally keeping this overlay to just the basic tooling for the ecosystem, and generally tooling that is maintained by the core team and kept in sync with language updates (`purs-tidy` is an exception, since it's under Nathan's account, but several core team members have maintainer access to it — including myself).

I would recommend that you instead make `purs-utils` available for use in PureScript projects in addition to the purescript overlay. That's what I did with [`slimlock`](https://github.com/thomashoneyman/slimlock), which I use in a few PureScript projects. You could perhaps use that as an example of how to package a minimal PureScript utility in nixpkgs for use alongside the overlay.

Plus, that way you don't have to wait for my admittedly slow reviews :)

**Comment by srghma** [comment]
flakes, ok, tnx!
